---

# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Check & Build

on: [push, pull_request]

jobs:

  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.4
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'
      - name: Install dependencies
        run: |
          echo '${{ github.ref }}'
          pnpm i --frozen-lockfile

      - name: Lint
        run: pnpm lint

  # on:
    # push:
  build:
    runs-on: ubuntu-latest
    needs: [check]
    if: github.event_name == 'push' && startsWith( github.ref, 'refs/tags' )

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.4
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Build & tag
        env:
          MSG: ${{ toJSON(github.event.commits.*.message) }}
        run: |
          pnpm run build -d dist -o acwing-reader.user.js
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          body_path: src/resources/update-log.txt
          prerelease: ${{ contains( github.ref_name, '-' ) }}
          files: dist/acwing-reader.user.js
